### ISSUE TITLE
Docker image currently not working

### ISSUE THREAD

**Issue by mattdmem** [BaobabLims/baobab.lims#120]
baobab_lims    | . 
baobab_lims    | daemon process started, pid=17
baobab_lims    |     from .transform import IOptimizer, IOrdered, IOptimizerChain, ITransformer
baobab_lims    |   File "/plone/instance/eggs/Products.AdvancedQuery-4.0-py2.7.egg/Products/AdvancedQuery/eval/transform.py", line 102, in <module>
baobab_lims    |     from .adapter import getSubscriptionAdapter, querySubscriptionAdapter
baobab_lims    |   File "/plone/instance/eggs/Products.AdvancedQuery-4.0-py2.7.egg/Products/AdvancedQuery/eval/adapter/__init__.py", line 44, in <module>
baobab_lims    |     from zope.interface.interfaces import ComponentLookupError
baobab_lims    | ImportError: cannot import name ComponentLookupError
baobab_lims    | ------
baobab_lims    | 2020-05-01T08:07:21 INFO ZServer HTTP server started at Fri May  1 08:07:21 2020
baobab_lims    | 	Hostname: 0.0.0.0
baobab_lims    | 	Port: 8080
baobab_lims    | Application running on pid=17
baobab_lims    | ------
baobab_lims    | 2020-05-01T08:07:25 ERROR Application Could not import Products.AdvancedQuery
baobab_lims    | Traceback (most recent call last):
baobab_lims    |   File "/plone/instance/eggs/Zope2-2.13.24-py2.7.egg/OFS/Application.py", line 606, in import_product
baobab_lims    |     product=__import__(pname, global_dict, global_dict, silly)
baobab_lims    |   File "/plone/instance/eggs/Products.AdvancedQuery-4.0-py2.7.egg/Products/AdvancedQuery/__init__.py", line 19, in <module>
baobab_lims    |     from .eval import eval as _eval, _notPassed
baobab_lims    |   File "/plone/instance/eggs/Products.AdvancedQuery-4.0-py2.7.egg/Products/AdvancedQuery/eval/__init__.py", line 18, in <module>
baobab_lims    |     from .interfaces import IQueryContext
baobab_lims    |   File "/plone/instance/eggs/Products.AdvancedQuery-4.0-py2.7.egg/Products/AdvancedQuery/eval/interfaces.py", line 9, in <module>
baobab_lims    |     from .transform import IOptimizer, IOrdered, IOptimizerChain, ITransformer
baobab_lims    |   File "/plone/instance/eggs/Products.AdvancedQuery-4.0-py2.7.egg/Products/AdvancedQuery/eval/transform.py", line 102, in <module>
baobab_lims    |     from .adapter import getSubscriptionAdapter, querySubscriptionAdapter
baobab_lims    |   File "/plone/instance/eggs/Products.AdvancedQuery-4.0-py2.7.egg/Products/AdvancedQuery/eval/adapter/__init__.py", line 44, in <module>
baobab_lims    |     from zope.interface.interfaces import ComponentLookupError
baobab_lims    | ImportError: cannot import name ComponentLookupError
baobab_lims    | ------
baobab_lims    | 2020-05-01T08:07:30 WARNING z3c.autoinclude resolve('Products.AdvancedQuery') raised import error: cannot import name ComponentLookupError
baobab_lims    | ------
baobab_lims    | 2020-05-01T08:07:31 WARNING plone.behavior Specifying 'for' in behavior 'Related items' if no 'factory' is given has no effect and is superfluous.

**Comment by zipho** [comment]
This PR should fix the issue, please update your baobab docker image to the latest in quay.

docker pull quay.io/baobab-lims/baobab-lims:latest

Please revert once tested and confirm if resolved. @mattdmem
