### ISSUE TITLE
analysis request

### ISSUE THREAD

**Issue by alanchristoffels** [BaobabLims/baobab.lims#20]
there is a lot of info on this "request" page that we do not need. Please remove this legacy info.

**Comment by hocinebendou** [comment]
Check commit [40b39b1](https://github.com/BaobabLims/baobab.lims/commit/40b39b1edb12e6877dc4f0366ee97a2748ee95aa)

**Comment by Dominique0804** [comment]
Have the standard analyses for human biobanking such as DNA concentration been added as default?
