### ISSUE TITLE
No need to store created kits in the inventory

### ISSUE THREAD

**Issue by hocinebendou** [BaobabLims/baobab.lims#25]
**Issue**
Last jamboree, Himo suggested that there's no need to store the kits because the kits are for shipping or to be processed; opened and store the kit's samples in freezers.

**Current**
Specifying storage for assembled kits is required

**Expected**
No need to store the kits

**Comment by hocinebendou** [comment]
Check commit [93b5f95](https://github.com/BaobabLims/baobab.lims/commit/93b5f9597497e038014284ffee850122984c9707)

**Comment by Dominique0804** [comment]
where are kits stored if not in inventory?
