### ISSUE TITLE
Issue with bin/buildout not finding packages 

### ISSUE THREAD

**Issue by zipho** [BaobabLims/baobab.lims#55]
Issue with bin/buildout not finding packages 

Development environment is affected as packages (eggs/wheels) not found when bin/buildout is ran.

**Comment by neolerusse** [comment]
Hi, i put here the ouput of the commande line "sudo -u plone_buildout bin/buildout" result.
is ther someone who can help me

Error: Couldn't find a distribution for 'baobab.lims'.
root@debianServeur:/usr/local/Plone/zeocluster# sudo -u plone_buildout bin/buildout
Develop: '/usr/local/Plone/zeocluster/src/bika.lims'
warning: no previously-included files matching '*pyc' found anywhere in distribution
Couldn't develop '/usr/local/Plone/zeocluster/src/boabab.lims' (not found)
Develop: '/usr/local/Plone/zeocluster/src/graphite.theme'
warning: no previously-included files matching '*pyc' found anywhere in distribution
Updating zeoserver.
Installing client1.
/usr/local/Plone/buildout-cache/eggs/setuptools-30.3.0-py2.7.egg/pkg_resources/__init__.py:184: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.
  stacklevel=1,
Couldn't find index page for 'baobab.lims' (maybe misspelled?)
Getting distribution for 'baobab.lims'.
Couldn't find index page for 'baobab.lims' (maybe misspelled?)
While:
  Installing client1.
  Getting distribution for 'baobab.lims'.
Error: Couldn't find a distribution for 'baobab.lims'.
