### ISSUE TITLE
Create a full docker version for baobab

### ISSUE THREAD

**Issue by hocinebendou** [BaobabLims/baobab.lims#65]

**Comment by thobalose** [comment]
@hocinebendou Kindly help me with more info.

**Comment by hocinebendou** [comment]
@thobalose We need to provide users the ability, using docker, to:

- test the lims on cloud (PWD)
- install the lims on there servers and make it accessible from outside, may be using nginx

**Comment by thobalose** [comment]
Hi @hocinebendou 

Users can have the ability to run Baobab LIMS in docker via these [instructions](https://github.com/BaobabLims/baobab.lims/blob/master/docker/README.md).

I will add NGINX as a reverse proxy.

**Comment by thobalose** [comment]
@hocinebendou 

Checkout https://github.com/BaobabLims/baobab.lims/pull/66
