### ISSUE TITLE
Error on intallation 

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [BaobabLims/baobab.lims#84]
I use docker installation for baobab.lims.. I found this error:
```
Successfully built 66728d118bad
baobab_lims is up-to-date
Starting baobab_nginx ... error

ERROR: for baobab_nginx  Cannot start service nginx: b'driver failed programming external connectivity on endpoint baobab_nginx (7d9243279b99ec8fda5929eb31e1cfee809a4972396fca7eaee7dffa96441ff2): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use'

ERROR: for nginx  Cannot start service nginx: b'driver failed programming external connectivity on endpoint baobab_nginx (7d9243279b99ec8fda5929eb31e1cfee809a4972396fca7eaee7dffa96441ff2): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use'
ERROR: Encountered errors while bringing up the projec
```
I try to use docker version

**Comment by thobalose** [comment]
@bioinfo-dirty-jobs 

Looks like you are already making use of port 80 in you machine.
You have two, maybe more, options:

- Running `ss -tlpn | grep 80`  and killing the PID with `kill -9 PID`

- Change port number in https://github.com/BaobabLims/baobab.lims/blob/master/docker-compose.yml#L9 to `81:80`. Thus, accessing installation at [localhost:81](http://localhost:81)

@hocinebendou Kindly note that this is not a bug but a configuration issue.

**Comment by hocinebendou** [comment]
Closed. Problem in user configuration. Thanks @thobalose
