### ISSUE TITLE
Couldn't find a distribution for 'baobab.lims'

### ISSUE THREAD

**Issue by jsan4christ** [BaobabLims/baobab.lims#88]
I have tried with Plone 5.1 (latest stable) and Plone 4.3.17 (old latest stable) with no success. 

Can someone advise what the supported versions of Plone are? is it okay to use any other versions? this is because bika.lims also looks specifically for versions less than 4.1.11 of Plone.

I can't seem to get older versions of the plone installer,

It would be helpful to know which group of versions would work together and where to find them.

**Comment by hocinebendou** [comment]
@jsan4christ. For dependency issues the newer versions seems not working. The version 4.1.11 works perfectly. Here a link for download: https://launchpad.net/plone/4.3/4.3.11/+download/Plone-4.3.11-r1-UnifiedInstaller.tgz

**Comment by jsan4christ** [comment]
Thanks @hocinebendou
