### ISSUE TITLE
Room temperature

### ISSUE THREAD

**Issue by alanchristoffels** [BaobabLims/baobab.lims#9]
When a room is created in the LIMS storage then the temperature is specified. There is no need to ask for this temperature repeatedly when shelfs and racks are configured. Remove the field "temperature" on subsequent pages after the Room has been configured.

**Comment by hocinebendou** [comment]
Check commit [fe27309](https://github.com/BaobabLims/baobab.lims/commit/fe27309f414e3275f519977ddafdb7264a4b8262)
